meta_product_name: "WODDI"
meta_title: "Woddi - Book your drop-in. Anytime. Anywhere."
meta_description: "Join us and book your drop-in anywhere in the world. Travelling? Working? Book your WOD hassle free with a few clicks and get to know some of the best crossfit boxes across the world."
meta_image: "og-image.png" # should exist in `app/assets/images/`
